### ISSUE TITLE
automatically create local directory if it doesn't exist

### ISSUE THREAD

**Issue by letitbk** [BrianAronson/docshop#4]
Brian, I realize that it will be great if this function can take care of managing the local directory automatically. For example, if there's no relevant directory in my local computer, I would create a local directory in this way. Here's an example for `s3write_csv`. Could you update this function as well as all other s3write_XX function in this package?

```
s3write_csv = function (data, object, aws = TRUE) 
{
    if (str_detect(object, "s3://")) {
        x <- rawConnection(raw(0), "w")
        readr::write_csv(data, x)
        put_object(rawConnectionValue(x), object = object)
    }
    else {
    	if (!dir.exists(dirname(object))) {
    		dir.create(dirname(object), recursive=TRUE)
    	}
        fwrite(data, object)
    }
}
```

Basically, you just need to these two lines;
```
    	if (!dir.exists(dirname(object))) {
    		dir.create(dirname(object), recursive=TRUE)
    	}
```

**Comment by BrianAronson** [comment]
Hi BK, done. 

dir.create doesn't overwrite folders that already exist. Instead, it just sends a warning saying it didn't create a folder because it already exists, which you disable with its showWarnings option. So I simplified those two lines to:

`dir.create(dirname(object), recursive= TRUE,showWarnings = FALSE)`

**Comment by letitbk** [comment]
Thanks much Brian! Awesome.
